# Generated by Django 4.1.7 on 2023-04-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='home',
            table='home',
        ),
    ]
