# Generated by Django 4.1.7 on 2023-04-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='home',
            table=None,
        ),
    ]
