# Generated by Django 4.1.7 on 2023-04-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_home_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.FilePathField(),
        ),
    ]
