# Generated by Django 4.1.7 on 2023-04-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_home_description_alter_home_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.TextField(),
        ),
    ]
