# Generated by Django 4.1.7 on 2023-04-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_home_image_alter_home_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
    ]
